services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"  

  ws-server:
    build:
      context: ./websocket
      dockerfile: Dockerfile
    depends_on:
      - redis
    restart: unless-stopped
    environment:
      - REDIS_URL=redis://redis:6379
    ports:
      - "8080:8080" 

  engine:
    build:
      context: ./worker
      dockerfile: Dockerfile
    depends_on:
      - redis
      - ws-server
    restart: unless-stopped
    environment:
      - REDIS_URL=redis://redis:6379

  express-server:
    build:
      context: ./backend-probo
      dockerfile: Dockerfile
    depends_on:
      - redis
      - engine
    restart: unless-stopped
    environment:
      - REDIS_URL=redis://redis:6379
    ports:
      - "3000:3000" 