services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"  
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 10s 

  ws-server:
    build:
      context: ./websockets
      dockerfile: Dockerfile
    depends_on:
      redis:
         condition: service_healthy
    restart: unless-stopped
    environment:
      - REDIS_URL=redis://redis:6379
    ports:
      - "8080:8080" 

  engine:
    build:
      context: ./worker
      dockerfile: Dockerfile
    depends_on:
      - redis
      - ws-server
    restart: on_failure 
    environment:
      - REDIS_URL=redis://redis:6379

  express-server:
    build:
      context: ./backend-probo
      dockerfile: Dockerfile
    depends_on:
      - redis
      - engine
    restart: unless-stopped
    environment:
      - REDIS_URL=redis://redis:6379
    ports:
      - "3000:3000" 