name: Continuous Integration

on: 
  push: 
    branches: [ master ]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set short SHA
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push Server
        uses: docker/build-push-action@v4
        with:
          context: ./backend-probo 
          file: ./backend-probo/Dockerfile
          push: true
          tags: pawanhfl/probo_server:${{ env.SHORT_SHA }}

      - name: Build and push Engine
        uses: docker/build-push-action@v4
        with:
          context: ./worker 
          file: ./worker/Dockerfile
          push: true
          tags: pawanhfl/probo-engine:${{ env.SHORT_SHA }} 

      - name: Build and push Websocket
        uses: docker/build-push-action@v4
        with:
          context: ./websocket/websocket  
          file: ./websocket/Dockerfile
          push: true
          tags: pawanhfl/probo_ws:${{ env.SHORT_SHA }}

      - name: clone system-ops , update and push
        run: |
          git clone https://github.com/spawan02/system_ops.git
          cd system_ops/probo
          sed -i "s|image: p  |g" server.yaml
          sed -i "s|image: pawanhfl/probo-engine:.*|image: pawanhfl/probo-engine:${{ env.SHORT_SHA }}|g" engine.yaml
          sed -i "s|image: pawanhfl/probo_ws:.*|image: pawanhfl/probo_ws:${{ env.SHORT_SHA }}|g" ws.yaml
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add system_ops/probo/server.yaml system_ops/probo/engine.yaml system_ops/probo/ws.yaml 
          git commit -m "Update images to new tags: ${{ env.SHORT_SHA }}"
          git push origin main